config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/ranking'
  root to: 'homes#home'

  resources :users, only: %i[index new edit update]

  resources :relationships, only: %i[create destroy]

  resources :friends do
    resources :comments,only: [:create,:destroy]
  end
  
  resources :posts, only: %i[index show create destroy new edit update]
  post 'posts/new', to: 'posts#create'

  resources :posts, only: %i[index show create] do
    resources :likes, only: %i[create destroy]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/:id', to: 'users#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    get 'logout/:id', to: 'users#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search', to: 'friends#search'

  get 'users/:id/friend', to: 'users#friend'
  get 'users/:id/post', to: 'users#post'
  get 'users/:id/like', to: 'users#like'
  get 'users/:id/micropost', to: 'users#micropost'
  get 'users/:id/admin', to: 'users#admin'
  get 'homes/term'
  get 'homes/privacy'
  get 'homes/sitenav'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end

  resources :microposts do
    resources :comment_microposts, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/friend.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: friends
#
#  id          :bigint           not null, primary key
#  description :text(65535)
#  model       :string(255)
#  name        :string(30)       not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#
class Friend < ApplicationRecord
  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validate :validate_name_not_including_comma
  validates :description, presence: true
  validates :description, length: { maximum: 400 }

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(friend_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      friend_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  private

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

app/controllers/friends_controller.rb
# frozen_string_literal: true

class FriendsController < ApplicationController
  before_action :login_check, only: %i[new edit update destroy]
  before_action :correct_user, only: %i[edit update]
  impressionist unique: [:session_hash]

  def index
    @friends = Friend.all.page(params[:page]).per(10).order(updated_at: :desc)
    @user = User.all
    @q = @friends.ransack(params[:q])
    @friends = @q.result(distinct: true)
  end

  def show
    @friend = Friend.find(params[:id])
    @user = @friend.user
    @comment = Comment.new
    @comments = @friend.comments.order(created_at: :asc)
    impressionist(@user, nil, :unique => [:session_hash])
    @page_views = @user.impressionist_count
  end

  def new
    @friend = Friend.new
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def update
    friend = Friend.find(params[:id])
    friend.update!(friend_params)
    redirect_to friends_url, notice: '募集内容の更新が完了しました。'
  end

  def destroy
    friend = Friend.find(params[:id])
    friend.destroy
    redirect_to friends_url, notice: '募集内容を削除しました。'
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user_id = current_user.id

    if @friend.save
      redirect_to @friend, notice: 'フレンド募集の投稿が完了しました。'
    else
      render :new
    end
  end

  private

  def friend_params
    params.require(:friend).permit(:name, :description, :email, :model)
  end

  def login_required
    redirect_to login_url unless current_user
  end

  def login_check
    unless user_signed_in?
      redirect_to new_user_session_path, notice: 'ログインしてください'
    end
  end

  def correct_user
    friend = Friend.find(params[:id])
    unless user_signed_in? && friend.user.id == current_user.id
      redirect_to friend, notice: '他ユーザーの投稿は編集できません'
    end
  end

  def user_logged_in?
    !current_user.nil?
  end
end

app/helpers/friends_helper.rb
# frozen_string_literal: true

module FriendsHelper
end

app/views/friends/_body.html.slim
.flexbox
    - @friends.includes(:user).each do |friend|
        .media.my-3.rounded.bg-white
            - if friend.user.image?
                = link_to image_tag(friend.user.image.url,size: '50x50',class: 'mx-3 my-2'),friend.user
            - else
                = link_to image_tag("/assets/default.jpg",size: '50x50', class: 'mx-3 my-2'),friend.user
            .media-body
                .h5
                    = link_to friend.name, friend,class: 'mt-2 mb-1 badge badge-pill btn-primary'
                = link_to(friend_path(friend)) do
                    .h6.mx-1.text-dark
                        = safe_join(friend.description.split("\n"),tag(:br))
                        //= simple_format(friend.description)
                .h8.mr-3.mb-3
                    |投稿日：
                    = I18n.l(friend.updated_at, format: :long)

app/views/friends/_form.html.slim
- if friend.errors.present?
  ul#error_explanation
    - friend.errors.full_messages.each do |message|
      li= message

= form_with model: @friend, local: true do |f|
    .form.group.row
        = f.label :model, class:'col-md-3 col-form-label'
    .col-md-1
        = f.select :model,[['PS5','PS5'],['PS4','PS4'],['PC','PC'],['XboxOne','XboxOne']] 
    br
    .form.group.row
        = f.label :name,"募集内容", class:'col-md-3 col-form-label'
    .col-md-1
        = f.select :name,[['フレンド募集','フレンド募集'],['クランメンバー募集','クランメンバー募集'],['クラン入隊希望','クラン入隊希望'],['その他','その他']] 
    br
    .form.group
        = f.label :description,"投稿内容（400字以内）"
        = f.text_area :description,placeholder: "募集内容の詳細を記入してください", rows: 10,class: 'form-control', id: 'friend_description'
    br
    = f.submit nil, class: 'btn btn-primary'

app/views/friends/edit.html.slim
- set_meta_tags title: "【Destiny2】募集内容の編集",
                site: "Right Guardians"
h2.text-center
    |募集内容の編集

.nav.justify-content-end
    = link_to '一覧', friends_path, class: 'nav-link'

.col-md-10.offset-md-1
    = render partial: 'form',locals: {friend: @friend}

app/views/friends/index.html.slim
- set_meta_tags title: "【Destiny2】フレンド募集掲示板",
                site: "Right Guardians"
.jumbotron.jumbotron-extend7
    h1.page-name1.text-center.mt-5
        .fas.fa-user-friends
        |募集一覧

- breadcrumb :friends_index
.container
    = breadcrumbs separator: " &rsaquo; "
hr
.col-md-10.offset-md-1
    = search_form_for @q,class: 'mb-5' do |f|
        .form.group.row
            = f.label :model_cont,'機種', class: 'col-sm-2 col-form-label'
            .col-sm-8
                = f.radio_button :model_cont, 'PS5'
                | PS5　
                = f.radio_button :model_cont, 'PS4'
                | PS4　
                = f.radio_button :model_cont, 'PC'
                | PC　
                = f.radio_button :model_cont, 'XboxOne'
                | XboxOne
        .form.group.row
            = f.label :name_cont,"募集内容", class: 'col-sm-2 col-form-label'
            .col-sm-8
                = f.radio_button :name_cont, 'フレンド募集'
                | フレンド募集　
                = f.radio_button :name_cont, 'クランメンバー募集'
                | クランメンバー募集　
                = f.radio_button :name_cont, 'クラン入隊希望'
                | クラン入隊希望　
                = f.radio_button :name_cont, 'その他'
                | その他
                      
        .form.group
            = f.submit class: 'btn btn-primary'
    hr
    = link_to '新規募集をする', new_friend_path, class: 'btn btn-primary mb-3'

.mb-3
    .col-md-10.offset-md-1
        = paginate @friends
        = page_entries_info @friends

.col-md-10.offset-md-1
    = render 'friends/body'

.mb-3
    .col-md-10.offset-md-1
        = paginate @friends

app/views/friends/new.html.slim
- set_meta_tags title: "【Destiny2】新規募集投稿",
                site: "Right Guardians"
.title5
    h2.text-center
        i.fas.fa-edit
        |募集投稿

.nav.justify-content-end
    = link_to '一覧', friends_path, class: 'nav-link'

.col-md-10.offset-md-1
    = render partial: 'form',locals: {friend: @friend,user: @user}

app/views/friends/show.html.slim
- set_meta_tags title: "【Destiny2】" + @friend.name + "の詳細",
                site: "Right Guardians"
- breadcrumb :friends_show,@user
br
.container
    = breadcrumbs separator: " &rsaquo; "
    hr
.title5
    h2.text-center
        |募集内容の詳細

.col-md-10.offset-md-1
    table.table.table-hover
        tbody
            tr
                th= Friend.human_attribute_name(:model)
                td= @friend.model
            tr
                th= User.human_attribute_name(:name)
                td= link_to @user.name,@user
            tr
                th= Friend.human_attribute_name(:募集内容)
                td= @friend.name
            tr
                th= Friend.human_attribute_name(:description)
                td= safe_join(@friend.description.split("\n"),tag(:br))
            tr
                th= Friend.human_attribute_name(:投稿日時)
                td= @friend.created_at.strftime('%Y/%m/%d %H:%M')
            tr
                th= Friend.human_attribute_name(:updated_at)
                td= @friend.updated_at.strftime('%Y/%m/%d %H:%M')
.col-md-10.offset-md-1.text-right
    i.fas.fa-eye
    h8
        = @page_views
        | views
.col-md-10.offset-md-1
    - if current_user&.admin?
        = link_to '削除',@friend,method: :delete,data: {confirm: "募集内容を削除します。よろしいですか？"},class: 'btn btn-danger'
    - if user_signed_in? && current_user.id == @user.id
        = link_to '編集',edit_friend_path,class: 'btn btn-primary mr-3 mb-3'
        = link_to '削除',@friend,method: :delete,data: {confirm: "募集内容を削除します。よろしいですか？"},class: 'btn btn-danger mb-3'
    .twitter
        <a href="https://twitter.com/share?url=http://guardians-community.com/friends/#{@friend.id}%0a&text=Destiny2で一緒に遊べる方を募集してます！%0aどなたか一緒に遊びませんか？%0a&hashtags=Destiny2%0a,Destiny2フレンド募集%0a,Right_Guardians" rel="nofollow" target="_blank" class="fab fa-twitter btn btn-gradient-3d-btn"> 募集内容をTwitterでシェアする</a>

br
.row
    .col-md-10.offset-md-1
        .comment-create
            h3.text-left.title
                i class="far fa-comment-dots"
                |コメント一覧
        hr
        #comments_area
            = render partial: 'comments/index', locals: {comments: @comments}
        br
        - if user_signed_in?
            .comment_create
                = render partial: 'comments/form', locals: {comment: @comment,friend: @friend}
        - else
            h7 
            = link_to "ログイン",new_user_session_path
            |すると、この募集にコメントすることが出来るようになります。