config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/ranking'
  root to: 'homes#home'

  resources :users, only: %i[index new edit update]

  resources :relationships, only: %i[create destroy]

  resources :friends do
    resources :comments,only: [:create,:destroy]
  end
  
  resources :posts, only: %i[index show create destroy new edit update]
  post 'posts/new', to: 'posts#create'

  resources :posts, only: %i[index show create] do
    resources :likes, only: %i[create destroy]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/:id', to: 'users#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    get 'logout/:id', to: 'users#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search', to: 'friends#search'

  get 'users/:id/friend', to: 'users#friend'
  get 'users/:id/post', to: 'users#post'
  get 'users/:id/like', to: 'users#like'
  get 'users/:id/micropost', to: 'users#micropost'
  get 'users/:id/admin', to: 'users#admin'
  get 'homes/term'
  get 'homes/privacy'
  get 'homes/sitenav'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end

  resources :microposts do
    resources :comment_microposts, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :bigint           not null, primary key
#  action     :string(255)      default(""), not null
#  checked    :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  comment_id :integer
#  friend_id  :integer
#  post_id    :integer
#  visited_id :integer          not null
#  visitor_id :integer          not null
#
# Indexes
#
#  index_notifications_on_comment_id  (comment_id)
#  index_notifications_on_friend_id   (friend_id)
#  index_notifications_on_post_id     (post_id)
#  index_notifications_on_visited_id  (visited_id)
#  index_notifications_on_visitor_id  (visitor_id)
#
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
  belongs_to :friend, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.slim
- visitor = notification.visitor
- visited = notification.visited
.col-md-6.mx-auto
  .form-inline
    span
      = link_to user_path(visitor) do
        strong
          = visitor.name
      = 'さんが'

      - case notification.action
      - when 'follow' then
        = "あなたをフォローしました"
      - when 'like' then
        = link_to 'あなたの投稿', notification.post, style: "font-weight: bold;"
        = "にいいねしました"
      - when 'comment' then
        - if notification.friend.user_id == visited.id
          = link_to "あなたの投稿", notification.friend, style: "font-weight: bold;"
        - else
          span
            = link_to friend_path(notification.friend) do
              //= image_tag avatar_url(notification.friend.user).to_s, class: "icon_mini" 
              strong
                = notification.friend.user.name + 'さんの投稿'
        = "にコメントしました"
        p.text-muted.mb-0
          = Comment.find_by(id: notification.comment_id)&.content

  .small.text-muted.text-right
    = time_ago_in_words(notification.created_at).upcase
  hr

app/views/notifications/index.html.slim
br
.h3.text-center
  i.far.fa-bell.fa-lg
    |通知
br
.col-md-6.mx-auto
  = link_to destroy_all_notifications_path, method: :delete,data: { confirm: '通知を全て削除してもよろしいですか？' }
    i.fas.fa-trash style="color: black;"
      h7 style="color: black;"
        |通知を全削除する
  hr
- notifications = @notifications.where.not(visitor_id: current_user.id)
- if notifications.exists?
  = render notifications
  .col-md-6.mx-auto
    = paginate notifications
- else
  .col-md-6.mx-auto
    p
      | 通知はありません