config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/ranking'
  root to: 'homes#home'

  resources :users, only: %i[index new edit update]

  resources :relationships, only: %i[create destroy]

  resources :friends do
    resources :comments,only: [:create,:destroy]
  end
  
  resources :posts, only: %i[index show create destroy new edit update]
  post 'posts/new', to: 'posts#create'

  resources :posts, only: %i[index show create] do
    resources :likes, only: %i[create destroy]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/:id', to: 'users#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    get 'logout/:id', to: 'users#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search', to: 'friends#search'

  get 'users/:id/friend', to: 'users#friend'
  get 'users/:id/post', to: 'users#post'
  get 'users/:id/like', to: 'users#like'
  get 'users/:id/micropost', to: 'users#micropost'
  get 'users/:id/admin', to: 'users#admin'
  get 'homes/term'
  get 'homes/privacy'
  get 'homes/sitenav'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end

  resources :microposts do
    resources :comment_microposts, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE)
#  carreer                :string(255)
#  clan                   :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  image                  :string(255)
#  level                  :integer
#  lightlevel             :integer
#  model                  :string(255)
#  name                   :string(255)
#  profession             :string(255)
#  profile                :text(65535)
#  psnid                  :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  sex                    :string(255)
#  steam                  :string(255)
#  strength               :float(24)
#  style                  :string(255)
#  timezone               :string(255)
#  twitter                :string(255)
#  voice                  :string(255)
#  weapon                 :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validates :profile, length: { maximum: 400 }

  has_many :posts, dependent: :destroy
  has_many :friends, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy  
  has_many :following_relationships,foreign_key: "follower_id", class_name: "Relationship",dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship",dependent: :destroy
  has_many :followers,through: :follower_relationships
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :comment_microposts, dependent: :destroy

  has_one_attached :image, dependent: :destroy

  mount_uploader :image, ImageUploader

  def friends
    Friend.where(user_id: id)
  end

  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'test123@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :admin_user

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to root_path, notice: 'アカウントを削除しました。'
  end

  private

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  # User.create(image: 'default.png')
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
  end

  # The path used after sign up.
  def after_sign_up_path_for(_resource)
    "/users/#{current_user.id}"
  end

  def after_update_path_for(_resource)
    user_path(id: current_user.id)
  end

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, notice: 'ゲストユーザーの変更・削除はできません。'
    end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to "/users/#{current_user.id}", notice: 'ゲストユーザーとしてログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  # end

  protected

  def after_sign_in_path_for(_resource)
    "/users/#{current_user.id}"
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def home; end

  def index
    @users = User.all.page(params[:page]).per(9).order(created_at: :desc)
    @q = @users.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @user = User.find(params[:id])
    @friends = @user.friends
    @relationship = Relationship.new
    @microposts = @user.microposts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to root_path, notice: 'プロフィールを更新しました。'
    else
      render :edit
    end
  end

  def friend
    @user = User.find(params[:id])
    @friends = @user.friends.page(params[:page]).per(10).order(updated_at: :desc)
  end

  def post
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(6).order(updated_at: :desc)
  end

  def like
    @user = User.find(params[:id])
    @likes = @user.likes.page(params[:page]).per(6).order(updated_at: :desc)
  end

  def micropost
    @user = User.find(params[:id])
    @microposts = @user.microposts.page(params[:page]).per(6).order(updated_at: :desc)
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params[:user].permit(:email)
  end

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profession, :image, :strength, :image_cache)
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_body.html.slim
- @users.each do |user|
    .col-md-4.col-xs-12
        .media.my-3.rounded.bg-white
            - if user.image?
                = link_to image_tag(user.image.url,class: 'm-3',size: '100x100'),user
            - else
                = link_to image_tag("/assets/default.jpg",class: 'm-3',size: '100x100'),user
            .media-body
                .h5 
                    = link_to user.name, user,class: 'mt-2 mb-1 badge badge-pill btn-primary'
                .h6
                    - if user.sex?
                        | 性別：
                        = user.sex
                    - else
                        | 性別：非公開
                .h6
                    - if user.strength?
                        | キルレ：
                        = user.strength
                    - else       
                        | キルレ：非公開
                .h8.mr-3.mb-3
                    |登録日：
                    = I18n.l(user.created_at, format: :long)

app/views/users/_follow.html.slim
= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f|
    = f.hidden_field :following_id
    = f.submit "フォローする", class: "btn btn-large btn-primary follow-btn"

app/views/users/_friends.html.slim
.col-md-10.offset-md-1
    - if current_user == @user
        - if @user.friends.empty?
            .posison-point
                p
                    |まだ募集投稿がありません
                p
                    |プロフィールを編集した後は、募集を投稿して仲間を探そう！
                p
                    = link_to "仲間を募集する",new_friend_path,class: "btn btn-primary dokidoki"
        - else @user.friends
            - @friends.includes(:user).each do |friend|
                .media.bg-white.m-3.rounded
                    - if friend.user.image?
                        = link_to image_tag(friend.user.image.url,class: 'mx-3 my-2',size: '50x50'),friend.user
                    - else
                        = link_to image_tag("/assets/default.jpg",class: 'mx-3 my-2',size: '50x50'),friend.user
                    .media-body
                        .h5 
                            = link_to friend.name,friend,class: 'mt-2 mb-1 badge badge-pill badge-primary'
                        = link_to(friend_path(friend)) do
                            .h6.mr-1.text-dark
                                = safe_join(friend.description.split("\n"),tag(:br))
                        .h8.mr-2
                            |投稿日：
                            = I18n.l(friend.updated_at, format: :long)
    - elsif @user.friends.empty?
        .posison-point
            p
                = @user.name
                |さんはまだ投稿していません
    - else @user.friends
        - @friends.includes(:user).each do |friend|
            .media.bg-white.m-3.rounded
                - if friend.user.image?
                    = link_to image_tag(friend.user.image.url,class: 'mx-3 my-2',size: '50x50'),friend.user
                - else
                    = link_to image_tag("/assets/default.jpg",class: 'mx-3 my-2',size: '50x50'),friend.user
                .media-body
                    .h5 
                        = link_to friend.name,friend,class: 'mt-2 mb-1 badge badge-pill badge-primary'
                    = link_to(friend_path(friend)) do
                        .h6.mr-1.text-dark
                            = simple_format(friend.description)
                    .h8.mr-2
                        |投稿日：
                        = I18n.l(friend.updated_at, format: :long)

app/views/users/_likes.html.slim
.row
   .col-md-12.offset-md-1
        .row.col-md-12
            - if current_user == @user
                - if @user.liked_posts.empty?
                    .posison-point
                        p
                            |まだいいねをしていません
                        p
                            |他のユーザーの投稿を見ていいねをしてみよう！
                        p
                            = link_to "投稿を見にいく",posts_path,class: "btn btn-primary dokidoki"
                - else @user.liked_posts
                    - @user.liked_posts.each do |post|
                        = link_to(post_path(post)) do
                            .card-group.m-2
                                .card style="width: 19rem"
                                    = image_tag post.image.url,class: 'card-img-top',size: '300x250'
                                    hr
                                    .card-body.text-dark
                                        = post.content
                                    //.card-footer
                                        = link_to "詳細","/posts/#{post.id}",class: "btn btn-primary"
            - elsif @user.liked_posts.empty?
                .posison-point.text-center
                    p 
                        = @user.name
                        |さんはまだいいねをしていません
            - else @user.liked_posts
                - @user.liked_posts.each do |post|
                    = link_to(post_path(post)) do
                        .card-group.m-2
                            .card style="width: 19rem"
                                = image_tag post.image.url,class: 'card-img-top',size: '300x250'
                                hr
                                .card-body.text-dark
                                    = post.content
                                //.card-footer
                                    = link_to "詳細","/posts/#{post.id}",class: "btn btn-primary"

app/views/users/_microposts.html.slim
.col-md-10.offset-md-1
    - if current_user == @user
        - if @user.microposts.empty?
            .posison-point
                p
                    |まだ募集投稿がありません
                p
                    |プロフィールを編集した後は、募集を投稿して仲間を探そう！
                p
                    = link_to "仲間を募集する",new_micropost_path,class: "btn btn-primary dokidoki"
        - else @user.microposts
            - @user.microposts.includes(:user).each do |micropost|
                .media.bg-white.m-3.rounded
                    - if micropost.user.image?
                        = link_to image_tag(micropost.user.image.url,class: 'mx-3 my-2',size: '50x50'),micropost.user
                    - else
                        = link_to image_tag("/assets/default.jpg",class: 'mx-3 my-2',size: '50x50'),micropost.user
                    .media-body
                        .h5 
                            = link_to micropost.name_type, micropost,class: 'mt-2 mb-1 mr-1 badge badge-pill btn-primary'
                            = link_to micropost.content, micropost,class: 'mt-2 mb-1 badge badge-pill btn-primary'
                        = link_to(micropost_path(micropost)) do
                            .h6.mr-1.text-dark
                                = simple_format(micropost.description)
                        .h8.mr-2
                            |投稿日：
                            = I18n.l(micropost.updated_at, format: :long)
    - elsif @user.microposts.empty?
        .posison-point
            p
                = @user.name
                |さんはまだ投稿していません
    - else @user.microposts
        - @user.microposts.includes(:user).each do |micropost|
            .media.bg-white.m-3.rounded
                - if micropost.user.image?
                    = link_to image_tag(micropost.user.image.url,class: 'mx-3 my-2',size: '50x50'),micropost.user
                - else
                    = link_to image_tag("/assets/default.jpg",class: 'mx-3 my-2',size: '50x50'),micropost.user
                .media-body
                    .h5 
                        = link_to micropost.name_type, micropost,class: 'mt-2 mb-1 mr-1 badge badge-pill btn-primary'
                        = link_to micropost.content, micropost,class: 'mt-2 mb-1 badge badge-pill btn-primary'
                    = link_to(micropost_path(micropost)) do
                        .h6.mr-1.text-dark
                            = simple_format(micropost.description)
                    .h8.mr-2
                        |投稿日：
                        = I18n.l(micropost.updated_at, format: :long)

app/views/users/_mypage.html.slim
.title6.text-center
    h2.fas.fa-user-circle
        | プロフィール

.thumbnail.mb-3
    - if @user.image?
        = image_tag @user.image.url(:thumb),class: "d-block mx-auto"
    - else
        = image_tag "/assets/default.jpg",class: "d-block mx-auto"
    end

app/views/users/_posts.html.slim
.row
   .col-md-12.offset-md-1
        .row.col-md-12
            - if current_user == @user
                - if @user.posts.empty?
                    .posison-point
                        p
                            |自慢の一枚への投稿はありません
                        p
                            |自慢の一枚を投稿して、他のユーザーにアピールしてみよう！
                        p
                            = link_to "新規投稿をする",new_post_path,class: "btn btn-primary dokidoki"
                - else @user.posts
                    - @user.posts.includes(:user).each do |post|
                        = link_to(post_path(post)) do
                            .card-group.m-2
                                .card style="width: 19rem"
                                    = image_tag post.image.url,class: 'card-img-top',size: '300x250'
                                    hr
                                    .card-body.text-dark
                                        = post.content
                                    //.card-footer
                                        = link_to "詳細","/posts/#{post.id}",class: "btn btn-primary"
            - elsif @user.posts.empty?
                .posison-point
                    p
                        = @user.name
                        |さんの投稿はありません
            - else @user.posts
                - @user.posts.includes(:user).each do |post|
                    = link_to(post_path(post)) do
                        .card-group.m-2
                            .card style="width: 19rem"
                                = image_tag post.image.url,class: 'card-img-top',size: '300x250'
                                hr
                                .card-body.text-dark
                                    = post.content
                                //.card-footer
                                    = link_to "詳細","/posts/#{post.id}",class: "btn btn-primary"

app/views/users/_profile.html.slim
.text-center
    - if user_signed_in? && current_user.id == @user.id
        = link_to '編集',edit_user_registration_path,class:"btn btn-primary float-right mb-2"
table.table.table
    tbody
        tr
            th= "名前"
            td= @user.name
        tr
            th= "PSID"
            td= @user.psnid
        tr
            th= "Steam ID"
            td= @user.steam
        tr
            th= "性別"
            td= @user.sex
        tr
            th= "機種"
            td= @user.model
        tr
            th= "メイン職業"
            td= @user.profession
        tr
            th= "メイン武器"
            td= @user.weapon
        tr
            th= "クラン名"
            td= @user.clan
        tr
            th= "シーズンランク"
            td= @user.level
        tr
            th= "パワーレベル"
            td= @user.lightlevel
        tr
            th= "キルレ"
            td= @user.strength
        tr
            th= "Destiny歴"
            td= @user.carreer
        tr
            th= "ボイスチャット"
            td= @user.voice
        tr
            th= "プレイスタイル"
            td= @user.style
        tr
            th= "プレイ時間"
            td= @user.timezone
        tr
            th= "Twitter"
            - if @user.twitter?
                td= link_to "Twitterアカウントを見にいく","https://twitter.com/#{@user.twitter}",class:"fab fa-twitter btn btn-gradient-3d-btn "
        tr
            th= "プロフィール"
            td= simple_format(@user.profile) 

app/views/users/_stats.html.slim
- @user ||= current_user
.stats
    a href="#{following_user_path(@user)}"
        #following.stat
            = @user.followings.count
            |フォロー
    a href="#{followers_user_path(@user)}"
        #followers.stat
            = @user.followers.count
            | フォロワー

app/views/users/_unfollow.html.slim
= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f|
    = f.submit "フォロー解除する",class: "btn btn-large btn-secondary follow-btn"

app/views/users/friend.html.slim
= render 'users/mypage'
= render 'users/profile'
= render 'users/nav'
= render 'users/friends'

app/views/users/post.html.slim
= render 'users/mypage'
= render 'users/profile'
= render 'users/nav'
= render 'users/posts'

app/views/users/show.html.slim
- set_meta_tags title: "【Destiny2】" + @user.name + "さんのプロフィール",
                site: "Right Guardians"
- breadcrumb :users_show, @user
br

.container
    = breadcrumbs separator: " &rsaquo; "
    hr
= render 'users/mypage'
.container
    .row.text-center
        .col-md-10.offset-md-1
            - if user_signed_in?
                = render 'follow_form'
            = render 'stats'


br
.container
   .row
        .col-md-10.offset-md-1
            = render 'users/profile'
            .twitter.mb-3
                <a href="https://twitter.com/share?url=http://guardians-community.com/users/#{@user.id}%0a&text=Destiny2で一緒に遊べる方を募集しています。%0aDestiny2用のマイページを作成したので%0a良ければ見てください！%0aぜひ一緒にDestiny2で遊びませんか？%0a&hashtags=Destiny2%0a,Destiny2フレンド募集" rel="nofollow" target="_blank" class="fab fa-twitter btn btn-gradient-3d-simple"> マイページをTwitterで拡散する</a>
            = render 'users/nav'

app/views/users/show_follow.html.slim
- set_meta_tags title: "【Destiny2】" + @user.name + "さんのフォローユーザー",
                site: "Right Guardians"
br
- breadcrumb :users_following,@user
.container
    = breadcrumbs separator: " &rsaquo; "
    hr

.following_title.text-center.my-5
  h3.fas.fa-users.h3-follow
    = @user.name
    |さんが
    br
    |フォローしているユーザー
hr
.row
  - if @users.empty?
    .posison-point1.text-center
      p #{@user.name}さんはまだフォローしていません
  - else
    - @user.followings.each do |user|
        .col-md-4.col-xs-12
          .media.my-3.rounded.bg-white
            - if user.image?
              = link_to image_tag(user.image.url,class: 'm-3',size: '100x100'),user
            - else
              = link_to image_tag("/assets/default.jpg",class: 'm-3',size: '100x100'),user
            .media-body
              .h5
                = link_to user.name, user,class: 'mt-2 mb-1 badge badge-pill badge-primary'
              .h6
                - if user.sex?
                  | 性別：
                  = user.sex
                - else
                  |性別：非公開
              .h6
                - if user.strength?
                  | キルレ：
                  = user.strength
                - else       
                  | キルレ：非公開
              .h8.mr-2.text_updated_at
                |登録日：
                = I18n.l(user.updated_at, format: :long)