config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'posts/index'
  get 'posts/show'
  get 'posts/ranking'
  root to: 'homes#home'

  resources :users, only: %i[index new edit update]

  resources :relationships, only: %i[create destroy]

  resources :friends do
    resources :comments,only: [:create,:destroy]
  end
  
  resources :posts, only: %i[index show create destroy new edit update]
  post 'posts/new', to: 'posts#create'

  resources :posts, only: %i[index show create] do
    resources :likes, only: %i[create destroy]
  end


  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    get 'users/:id', to: 'users#show'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
    get 'logout/:id', to: 'users#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  get 'search', to: 'friends#search'

  get 'users/:id/friend', to: 'users#friend'
  get 'users/:id/post', to: 'users#post'
  get 'users/:id/like', to: 'users#like'
  get 'users/:id/micropost', to: 'users#micropost'
  get 'users/:id/admin', to: 'users#admin'
  get 'homes/term'
  get 'homes/privacy'
  get 'homes/sitenav'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :notifications, only: :index do
    collection do
      delete 'destroy_all'
    end
  end

  resources :microposts do
    resources :comment_microposts, only: [:create,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id          :bigint           not null, primary key
#  content     :string(255)      not null
#  description :text(65535)      not null
#  model       :string(255)      not null
#  name_type   :string(255)      not null
#  raid_time   :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_microposts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comment_microposts, dependent: :destroy

  validates :content, presence: true
  validates :model, presence: true
  validates :name_type, presence: true
  validates :description, presence: true
  validates :description, length: { maximum: 400 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :login_check, only: %i[new edit update destroy]
  before_action :currect_user, only: %i[edit update]

  def index
    @microposts = Micropost.all.page(params[:page]).per(10).order(updated_at: :desc)
    @q = @microposts.ransack(params[:q])
    @microposts = @q.result(distinct: true)
  end

  def show
    @micropost = Micropost.find(params[:id])
    @user = @micropost.user
    @comment_micropost = CommentMicropost.new
    @comment_microposts = @micropost.comment_microposts
    impressionist(@user, nil, :unique => [:session_hash])
    @page_views = @user.impressionist_count
  end

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = Micropost.new(micropost_params)
    @micropost.user_id = current_user.id
    if @micropost.save
      redirect_to @micropost, notice: '投稿が完了しました。'
    else
      render :new
    end
  end

  def edit
    @micropost = Micropost.find(params[:id])
  end

  def update
    micropost = Micropost.find(params[:id])
    micropost.update!(micropost_params)
    redirect_to micropost_path, notice: '募集内容の更新が完了しました。' 
  end

  def destroy
    micropost = Micropost.find(params[:id])
    micropost.destroy
    redirect_to microposts_url, notice: '募集内容を削除しました。' 
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :description, :model, :name_type, :raid_time)
  end

  def login_required
    redirect_to login_url unless current_user
  end

  def login_check
    unless user_signed_in?
      redirect_to new_user_session_path, notice: 'ログインしてください'
    end
  end

  def currect_user
    micropost = Micropost.find(params[:id])
    unless user_signed_in? && micropost.user.id == current_user.id
      redirect_to micropost, notice: '他ユーザーの投稿は編集できません'
    end
  end

  def user_logged_in?
    !current_user.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.slim
- if micropost.errors.present?
  ul#error_explanation
    - micropost.errors.full_messages.each do |message|
      li= message

= form_with model: micropost, local: true do |f|
  .form.group
    = f.label :model
  .col-md-1
    = f.select :model,[['PS5','PS5'],['PS4','PS4'],['PC','PC'],['XboxOne','XboxOne']] 
  br
  .form.group
    = f.label :content
  .col-md-1
    = f.select :content,[['門弟の誓い','門弟の誓い'],['ガラスの間','ガラスの間'],['最後の望み','最後の望み'],['救済の庭園','救済の庭園'],['ディープストーン・クリプト','ディープストーン・クリプト'],['悲観の冠','悲観の冠'],['過去の惨劇','過去の惨劇'],['星々のスパイア','星々のスパイア'],['世界を食らう船','世界を食らう船'],['リヴァイアサン','リヴァイアサン']]
  br
  .form.group
    = f.label :name_type
  .col-md-1
    = f.select :name_type,[['お誘い待ち','お誘い待ち'],['ホストで募集','ホストで募集']]
  br
  .form.group
    = f.label :description,"投稿内容（400字以内）"
    = f.text_area :description, placeholder: "400文字以内で募集内容の詳細を記入してください。", rows: 10,class: 'form-control'
  br
  = f.submit class: 'btn btn-primary'

app/views/microposts/edit.html.slim
- set_meta_tags title: "【Destiny2】レイド募集投稿",
                site: "Right Guardians"
.title5
    h2.text-center
        i.fas.fa-edit
        |ガラスの間の募集編集

.nav.justify-content-end
    = link_to '一覧', microposts_path, class: 'nav-link'

.container
  .row
    .col-md-6.col-12
      .card
        .card-body
          = render 'form', micropost: @micropost

app/views/microposts/index.html.slim
- set_meta_tags title: "【Destiny2】レイド募集専用掲示板",
                site: "Right Guardians"
- breadcrumb :microposts_index

.jumbotron.jumbotron-extend8
    h1.page-name1.text-center.mt-5
        |レイド募集

.container
    = breadcrumbs separator: " &rsaquo; "

hr
.container
  .row
    .col-12.col-md-8.offset-md-2
      = search_form_for @q,class: 'mb-5' do |f|
        .form.group.row
          = f.label :name_type_cont,'▼募集タイプ', class: 'col-sm-3 col-form-label'
          .col-sm-8
            = f.radio_button :name_type_cont,'お誘い待ち'
            |お誘い待ち　
            = f.radio_button :name_type_cont,'ホストで募集'
            |ホストで募集
        br
        .form.group
            = f.submit class: 'btn btn-primary'
        hr

.container
  .row
    .col-12.col-md-8.offset-md-2
      = link_to "新規募集をする", new_micropost_path, class: "btn btn-primary"
      hr
.container
  .row
    .col-12.col-md-8.offset-md-2
      = paginate @microposts
      = page_entries_info @microposts
.container
  .row
    .col-12.col-md-8.offset-md-2
      - @microposts.includes(:user).each do |micropost|
        .cord.bg-light.mt-3.rounded
          .card-header.bg-transparent
            - if micropost.user.image?
              = link_to image_tag(micropost.user.image.url,size: '25x25',class: 'mr-3 rounded-circle'),micropost.user
            - else
              = link_to image_tag("/assets/default.jpg",size: '25x25', class: 'mr-3 rounded-circle'),micropost.user
            = link_to micropost.name_type, micropost,class: 'mt-2 mb-1 mr-1 badge badge-pill btn-primary'
            = link_to micropost.content, micropost,class: 'mt-2 mb-1 badge badge-pill btn-primary'
            br
            = link_to(micropost_path(micropost)) do
              .cord-body.text-dark
                .card-text
                  .h6.text-left.mt-3
                    = safe_join(micropost.description.split("\n"),tag(:br))
              .cord-footer.text-dark
                h8
                  |投稿日：
                  = I18n.l(micropost.updated_at, format: :long)
.container
  .row
    .col-12.col-md-8.offset-md-2
      br
      = paginate @microposts

app/views/microposts/new.html.slim
- set_meta_tags title: "【Destiny2】レイド募集投稿",
                site: "Right Guardians"
.title5
  h3.text-center
    |レイド募集投稿

.nav.justify-content-end
    = link_to '一覧', microposts_path, class: 'nav-link'

.col-md-10.offset-md-1
  = render 'form', micropost: @micropost

app/views/microposts/show.html.slim
- set_meta_tags title: "【Destiny2】レイド募集内容",
                site: "Right Guardians"
- breadcrumb :microposts_show,@user
br
.container
    = breadcrumbs separator: " &rsaquo; "
    hr
.title5
    h2.text-center
      |募集内容の詳細

.col-md-10.offset-md-1
  table.table.table-hover
      tbody
        tr
          th= Micropost.human_attribute_name(:model)
          td= @micropost.model
        tr
          th= Micropost.human_attribute_name(:content)
          td= @micropost.content
        tr
          th= User.human_attribute_name(:name)
          td= link_to @user.name,@user
        tr
          th= Micropost.human_attribute_name(:name_type)
          td= @micropost.name_type
        tr
          th= Micropost.human_attribute_name(:description)
          td= safe_join(@micropost.description.split("\n"),tag(:br))
        tr
          th= Micropost.human_attribute_name(:投稿日時)
          td= @micropost.created_at.strftime('%Y/%m/%d %H:%M')
        tr
          th= Micropost.human_attribute_name(:updated_at)
          td= @micropost.updated_at.strftime('%Y/%m/%d %H:%M')
.col-md-10.offset-md-1
  - if current_user&.admin?
    = link_to '削除',@micropost,method: :delete,data: {confirm: "募集内容を削除します。よろしいですか？"},class: 'btn btn-danger'
  - if user_signed_in? && current_user.id == @user.id
    = link_to '編集',edit_micropost_path,class: 'btn btn-primary mr-3 mb-3'
    = link_to '削除',@micropost,method: :delete,data: {confirm: "募集内容を削除します。よろしいですか？"},class: 'btn btn-danger mb-3'
  .twitter
    <a href="https://twitter.com/share?url=http://guardians-community.com/microposts/#{@micropost.id}%0a&text=#{@micropost.content}へ一緒に行きませんか？%0a&hashtags=Destiny2%0a,Right_Guardians" rel="nofollow" target="_blank" class="fab fa-twitter btn btn-gradient-3d-btn"> 募集内容をTwitterでシェアする</a>

br
.row
  .col-md-10.offset-md-1
    .comment-create
      h3.text-left.title
        i class="far fa-comment-dots"
        |コメント一覧
    hr
    #comments_area
      = render partial: 'comment_microposts/index', locals: { comment_microposts: @comment_microposts }
    br
    - if user_signed_in?
      .comment_create
        = render partial: 'comment_microposts/form', locals: { comment_micropost: @comment_micropost,micropost: @micropost }
    - else
      h7 
      = link_to "ログイン",new_user_session_path
      |するとこの募集にコメント出来るようになります。